/-
Copyright (c) 2018 Patrick Massot. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Patrick Massot, Johannes Hölzl
-/
module

public import Mathlib.Topology.UniformSpace.AbstractCompletion
public import Mathlib.Topology.UniformSpace.CauchyContinuous

/-!
# Hausdorff completions of uniform spaces

The goal is to construct a left-adjoint to the inclusion of complete Hausdorff uniform spaces
into all uniform spaces. Any uniform space `α` gets a completion `Completion α` and a morphism
(i.e. uniformly continuous map) `(↑) : α → Completion α` which solves the universal
mapping problem of factorizing morphisms from `α` to any complete Hausdorff uniform space `β`.
It means any uniformly continuous `f : α → β` gives rise to a unique morphism
`Completion.extension f hf : Completion α → β` such that `f = Completion.extension f hf ∘ (↑)`,
where `hf` proves that `f` is uniformly continuous.

Beware that `(↑)` is not injective if `α` is not Hausdorff. But its image is always
dense. The adjoint functor acting on morphisms is then constructed by the usual abstract nonsense.
For every uniform spaces `α` and `β`, it turns a uniformly continuous `f : α → β` into a morphism
  `Completion.map f hf : Completion α → Completion β`
such that
  `(↑) ∘ f = (Completion.map f hf) ∘ (↑)`.
This construction is compatible with composition.

In this file we introduce the following concepts:

* `CauchyFilter α` the uniform completion of the uniform space `α` (using Cauchy filters).
  These are not minimal filters.

* `Completion α := Quotient (separationSetoid (CauchyFilter α))` the Hausdorff completion.

## References

This formalization is mostly based on
  N. Bourbaki: General Topology
  I. M. James: Topologies and Uniformities
From a slightly different perspective in order to reuse material in `Topology.UniformSpace.Basic`.
-/

@[expose] public section

noncomputable section

open Filter Set
open scoped SetRel Uniformity Topology

universe u v w

/-- Space of Cauchy filters

This is essentially the completion of a uniform space. The embeddings are the neighbourhood filters.
This space is not minimal, the separated uniform space (i.e. quotiented on the intersection of all
entourages) is necessary for this.
-/
def CauchyFilter (α : Type u) [UniformSpace α] : Type u :=
  { f : Filter α // Cauchy f }

namespace CauchyFilter

section

variable {α : Type u} [UniformSpace α]
variable {β : Type v}
variable [UniformSpace β]

instance (f : CauchyFilter α) : NeBot f.1 := f.2.1

/-- The pairs of Cauchy filters generated by a set. -/
def gen (s : SetRel α α) : SetRel (CauchyFilter α) (CauchyFilter α) :=
  { p | s ∈ p.1.val ×ˢ p.2.val }

theorem monotone_gen : Monotone (gen : SetRel α α → _) :=
  monotone_ofPred fun p => @Filter.monotone_mem _ (p.1.val ×ˢ p.2.val)

-- Porting note: this was a calc proof, but I could not make it work
private theorem symm_gen : map Prod.swap ((𝓤 α).lift' gen) ≤ (𝓤 α).lift' gen := by
  let f := fun s : SetRel α α =>
        { p : CauchyFilter α × CauchyFilter α | s ∈ (p.2.val ×ˢ p.1.val : Filter (α × α)) }
  have h₁ : map Prod.swap ((𝓤 α).lift' gen) = (𝓤 α).lift' f := by
    delta gen
    simp [f, map_lift'_eq, monotone_ofPred, Filter.monotone_mem, Function.comp_def,
      image_swap_eq_preimage_swap]
  have h₂ : (𝓤 α).lift' f ≤ (𝓤 α).lift' gen :=
    uniformity_lift_le_swap
      (monotone_principal.comp
        (monotone_ofPred fun p => @Filter.monotone_mem _ (p.2.val ×ˢ p.1.val)))
      (by
        have h := fun p : CauchyFilter α × CauchyFilter α => @Filter.prod_comm _ _ p.2.val p.1.val
        simp only [Function.comp, h, mem_map, f]
        exact le_rfl)
  exact h₁.trans_le h₂

private theorem subset_gen_relComp {s t : SetRel α α} : gen s ○ gen t ⊆ gen (s ○ t) :=
  fun ⟨f, g⟩ ⟨h, h₁, h₂⟩ =>
  let ⟨t₁, (ht₁ : t₁ ∈ f.val), t₂, (ht₂ : t₂ ∈ h.val), (h₁ : t₁ ×ˢ t₂ ⊆ s)⟩ := mem_prod_iff.mp h₁
  let ⟨t₃, (ht₃ : t₃ ∈ h.val), t₄, (ht₄ : t₄ ∈ g.val), (h₂ : t₃ ×ˢ t₄ ⊆ t)⟩ := mem_prod_iff.mp h₂
  have : t₂ ∩ t₃ ∈ h.val := inter_mem ht₂ ht₃
  let ⟨x, xt₂, xt₃⟩ := h.property.left.nonempty_of_mem this
  (f.val ×ˢ g.val).sets_of_superset (prod_mem_prod ht₁ ht₄)
    fun ⟨a, b⟩ ⟨(ha : a ∈ t₁), (hb : b ∈ t₄)⟩ =>
    ⟨x, h₁ (show (a, x) ∈ t₁ ×ˢ t₂ from ⟨ha, xt₂⟩), h₂ (show (x, b) ∈ t₃ ×ˢ t₄ from ⟨xt₃, hb⟩)⟩

private theorem comp_gen : ((𝓤 α).lift' gen).lift' (fun s ↦ s ○ s) ≤ (𝓤 α).lift' gen :=
  calc
        ((𝓤 α).lift' gen).lift' (fun s ↦ s ○ s)
    _ = (𝓤 α).lift' fun s ↦ gen s ○ gen s := by
      rw [lift'_lift'_assoc]
      · exact monotone_gen
      · exact monotone_id.relComp monotone_id
    _ ≤ (𝓤 α).lift' fun s ↦ gen <| s ○ s := lift'_mono' fun _ _hs => subset_gen_relComp
    _ = ((𝓤 α).lift' fun s : SetRel α α => s ○ s).lift' gen := by
      rw [lift'_lift'_assoc]
      · exact monotone_id.relComp monotone_id
      · exact monotone_gen
    _ ≤ (𝓤 α).lift' gen := lift'_mono comp_le_uniformity le_rfl

instance : UniformSpace (CauchyFilter α) :=
  UniformSpace.ofCore
    { uniformity := (𝓤 α).lift' gen
      refl := principal_le_lift'.2 fun _s hs ⟨a, b⟩ =>
        fun (a_eq_b : a = b) => a_eq_b ▸ a.property.right hs
      symm := by exact symm_gen
      comp := by exact comp_gen }

theorem mem_uniformity {s : Set (CauchyFilter α × CauchyFilter α)} :
    s ∈ 𝓤 (CauchyFilter α) ↔ ∃ t ∈ 𝓤 α, gen t ⊆ s :=
  mem_lift'_sets monotone_gen

theorem basis_uniformity {ι : Sort*} {p : ι → Prop} {s : ι → SetRel α α} (h : (𝓤 α).HasBasis p s) :
    (𝓤 (CauchyFilter α)).HasBasis p (gen ∘ s) :=
  h.lift' monotone_gen

theorem mem_uniformity' {s : Set (CauchyFilter α × CauchyFilter α)} :
    s ∈ 𝓤 (CauchyFilter α) ↔ ∃ t ∈ 𝓤 α, ∀ f g : CauchyFilter α, t ∈ f.1 ×ˢ g.1 → (f, g) ∈ s := by
  refine mem_uniformity.trans (exists_congr (fun t => and_congr_right_iff.mpr (fun _h => ?_)))
  exact ⟨fun h _f _g ht => h ht, fun h _p hp => h _ _ hp⟩

/-- Embedding of `α` into its completion `CauchyFilter α` -/
def pureCauchy (a : α) : CauchyFilter α :=
  ⟨pure a, cauchy_pure⟩

theorem isUniformInducing_pureCauchy : IsUniformInducing (pureCauchy : α → CauchyFilter α) :=
  ⟨have : (preimage fun x : α × α => (pureCauchy x.fst, pureCauchy x.snd)) ∘ gen = id :=
      funext fun s =>
        Set.ext fun ⟨a₁, a₂⟩ => by simp [preimage, gen, pureCauchy]
    calc
      comap (fun x : α × α => (pureCauchy x.fst, pureCauchy x.snd)) ((𝓤 α).lift' gen) =
          (𝓤 α).lift' ((preimage fun x : α × α => (pureCauchy x.fst, pureCauchy x.snd)) ∘ gen) :=
        comap_lift'_eq
      _ = 𝓤 α := by simp [this]
      ⟩

theorem isUniformEmbedding_pureCauchy : IsUniformEmbedding (pureCauchy : α → CauchyFilter α) where
  __ := isUniformInducing_pureCauchy
  injective _a₁ _a₂ h := pure_injective <| Subtype.ext_iff.1 h

theorem denseRange_pureCauchy : DenseRange (pureCauchy : α → CauchyFilter α) := fun f => by
  have h_ex : ∀ s ∈ 𝓤 (CauchyFilter α), ∃ y : α, (f, pureCauchy y) ∈ s := fun s hs =>
    let ⟨t'', ht''₁, (ht''₂ : gen t'' ⊆ s)⟩ := (mem_lift'_sets monotone_gen).mp hs
    let ⟨t', ht'₁, ht'₂⟩ := comp_mem_uniformity_sets ht''₁
    have : t' ∈ f.val ×ˢ f.val := f.property.right ht'₁
    let ⟨t, ht, (h : t ×ˢ t ⊆ t')⟩ := mem_prod_same_iff.mp this
    let ⟨x, (hx : x ∈ t)⟩ := f.property.left.nonempty_of_mem ht
    have : t'' ∈ f.val ×ˢ pure x :=
      mem_prod_iff.mpr
        ⟨t, ht, { y : α | (x, y) ∈ t' }, h <| mk_mem_prod hx hx,
          fun ⟨a, b⟩ ⟨(h₁ : a ∈ t), (h₂ : (x, b) ∈ t')⟩ =>
          ht'₂ <| SetRel.prodMk_mem_comp (@h (a, x) ⟨h₁, hx⟩) h₂⟩
    ⟨x, ht''₂ <| by dsimp [gen]; exact this⟩
  simp only [closure_eq_cluster_pts, ClusterPt, nhds_eq_uniformity, lift'_inf_principal_eq,
    Set.inter_comm _ (range pureCauchy), mem_ofPred_eq]
  refine (lift'_neBot_iff ?_).mpr (fun s hs => ?_)
  · exact monotone_const.inter monotone_preimage
  · let ⟨y, hy⟩ := h_ex s hs
    have : pureCauchy y ∈ range pureCauchy ∩ { y : CauchyFilter α | (f, y) ∈ s } :=
      ⟨mem_range_self y, hy⟩
    exact ⟨_, this⟩

theorem isDenseInducing_pureCauchy : IsDenseInducing (pureCauchy : α → CauchyFilter α) :=
  isUniformInducing_pureCauchy.isDenseInducing denseRange_pureCauchy

theorem isDenseEmbedding_pureCauchy : IsDenseEmbedding (pureCauchy : α → CauchyFilter α) :=
  isUniformEmbedding_pureCauchy.isDenseEmbedding denseRange_pureCauchy

theorem nonempty_cauchyFilter_iff : Nonempty (CauchyFilter α) ↔ Nonempty α := by
  constructor <;> rintro ⟨c⟩
  · have := eq_univ_iff_forall.1 isDenseEmbedding_pureCauchy.isDenseInducing.closure_range c
    obtain ⟨_, ⟨_, a, _⟩⟩ := mem_closure_iff.1 this _ isOpen_univ trivial
    exact ⟨a⟩
  · exact ⟨pureCauchy c⟩

section

instance : CompleteSpace (CauchyFilter α) :=
  completeSpace_extension isUniformInducing_pureCauchy denseRange_pureCauchy fun f hf =>
    let f' : CauchyFilter α := ⟨f, hf⟩
    have : map pureCauchy f ≤ (𝓤 <| CauchyFilter α).lift' (preimage (Prod.mk f')) :=
      le_lift'.2 fun _ hs =>
        let ⟨t, ht₁, ht₂⟩ := (mem_lift'_sets monotone_gen).mp hs
        let ⟨t', ht', (h : t' ×ˢ t' ⊆ t)⟩ := mem_prod_same_iff.mp (hf.right ht₁)
        have : t' ⊆ { y : α | (f', pureCauchy y) ∈ gen t } := fun x hx =>
          (f ×ˢ pure x).sets_of_superset (prod_mem_prod ht' hx) h
        f.sets_of_superset ht' <| Subset.trans this (preimage_mono ht₂)
    ⟨f', by simpa [nhds_eq_uniformity]⟩

end

instance [Inhabited α] : Inhabited (CauchyFilter α) :=
  ⟨pureCauchy default⟩

instance [h : Nonempty α] : Nonempty (CauchyFilter α) :=
  h.recOn fun a => Nonempty.intro <| CauchyFilter.pureCauchy a

section Extend

/--
Extend a uniformly continuous function `f : α → β` into a complete separated uniform space to a
uniformly continuous function `CauchyFilter α → β` that agrees with `f` on `α`
(`CauchyFilter.extend_pureCauchy`).
-/
@[nolint unusedArguments]
def extend [CompleteSpace β] [T0Space β] (f : α → β) (_hf : UniformContinuous f) :
    CauchyFilter α → β :=
  isDenseInducing_pureCauchy.extend f

variable [CompleteSpace β] [T0Space β]

theorem extend_pureCauchy {f : α → β} (hf : UniformContinuous f) (a : α) :
    extend f hf (pureCauchy a) = f a :=
  uniformly_extend_of_ind isUniformInducing_pureCauchy denseRange_pureCauchy hf _

@[fun_prop]
theorem uniformContinuous_extend {f : α → β} (hf : UniformContinuous f) :
    UniformContinuous (extend f hf) :=
  uniformContinuous_uniformly_extend isUniformInducing_pureCauchy denseRange_pureCauchy hf

end Extend

theorem inseparable_iff {f g : CauchyFilter α} : Inseparable f g ↔ f.1 ×ˢ g.1 ≤ 𝓤 α :=
  (basis_uniformity (basis_sets _)).inseparable_iff_uniformity

theorem inseparable_iff_of_le_nhds {f g : CauchyFilter α} {a b : α}
    (ha : f.1 ≤ 𝓝 a) (hb : g.1 ≤ 𝓝 b) : Inseparable a b ↔ Inseparable f g := by
  rw [← tendsto_id'] at ha hb
  rw [inseparable_iff, (ha.comp tendsto_fst).inseparable_iff_uniformity (hb.comp tendsto_snd)]
  simp only [Function.comp_apply, id_eq, Prod.mk.eta, ← Function.id_def, tendsto_id']

theorem inseparable_lim_iff [CompleteSpace α] {f g : CauchyFilter α} :
    haveI := f.2.1.nonempty; Inseparable (lim f.1) (lim g.1) ↔ Inseparable f g :=
  inseparable_iff_of_le_nhds f.2.le_nhds_lim g.2.le_nhds_lim

end

theorem cauchyFilter_eq {α : Type*} [UniformSpace α] [CompleteSpace α] [T0Space α]
    {f g : CauchyFilter α} :
    haveI := f.2.1.nonempty; lim f.1 = lim g.1 ↔ Inseparable f g := by
  rw [← inseparable_iff_eq, inseparable_lim_iff]

section

theorem separated_pureCauchy_injective {α : Type*} [UniformSpace α] [T0Space α] :
    Function.Injective fun a : α => SeparationQuotient.mk (pureCauchy a) := fun a b h ↦
  Inseparable.eq <| (inseparable_iff_of_le_nhds (pure_le_nhds a) (pure_le_nhds b)).2 <|
    SeparationQuotient.mk_eq_mk.1 h

end

end CauchyFilter

open CauchyFilter Set

namespace UniformSpace

variable (α : Type*) [UniformSpace α]
variable {β : Type*} [UniformSpace β]
variable {γ : Type*} [UniformSpace γ]

/-- Hausdorff completion of `α` -/
def Completion := SeparationQuotient (CauchyFilter α)

namespace Completion

instance inhabited [Inhabited α] : Inhabited (Completion α) :=
  inferInstanceAs <| Inhabited (Quotient _)

instance uniformSpace : UniformSpace (Completion α) :=
  fast_instance% SeparationQuotient.instUniformSpace

instance completeSpace : CompleteSpace (Completion α) :=
  SeparationQuotient.instCompleteSpace

instance t0Space : T0Space (Completion α) := SeparationQuotient.instT0Space

variable {α} in
/-- The map from a uniform space to its completion. -/
@[coe] def coe' : α → Completion α := SeparationQuotient.mk ∘ pureCauchy

/-- Automatic coercion from `α` to its completion. Not always injective. -/
instance : Coe α (Completion α) :=
  ⟨coe'⟩

-- note [use has_coe_t]
protected theorem coe_eq : ((↑) : α → Completion α) = SeparationQuotient.mk ∘ pureCauchy := rfl

theorem isUniformInducing_coe : IsUniformInducing ((↑) : α → Completion α) :=
  SeparationQuotient.isUniformInducing_mk.comp isUniformInducing_pureCauchy

theorem comap_coe_eq_uniformity :
    ((𝓤 _).comap fun p : α × α => ((p.1 : Completion α), (p.2 : Completion α))) = 𝓤 α :=
  (isUniformInducing_coe _).1

variable {α} in
theorem denseRange_coe : DenseRange ((↑) : α → Completion α) :=
  SeparationQuotient.surjective_mk.denseRange.comp denseRange_pureCauchy
    SeparationQuotient.continuous_mk

/-- The Hausdorff completion as an abstract completion. -/
def cPkg {α : Type*} [UniformSpace α] : AbstractCompletion α where
  space := Completion α
  coe := (↑)
  uniformStruct := by infer_instance
  complete := by infer_instance
  separation := by infer_instance
  isUniformInducing := Completion.isUniformInducing_coe α
  dense := Completion.denseRange_coe

instance AbstractCompletion.inhabited : Inhabited (AbstractCompletion α) :=
  ⟨cPkg⟩

attribute [local instance]
  AbstractCompletion.uniformStruct AbstractCompletion.complete AbstractCompletion.separation

theorem nonempty_completion_iff : Nonempty (Completion α) ↔ Nonempty α :=
  cPkg.dense.nonempty_iff.symm

@[fun_prop]
theorem uniformContinuous_coe : UniformContinuous ((↑) : α → Completion α) :=
  cPkg.uniformContinuous_coe

theorem continuous_coe : Continuous ((↑) : α → Completion α) :=
  cPkg.continuous_coe

theorem isUniformEmbedding_coe [T0Space α] : IsUniformEmbedding ((↑) : α → Completion α) :=
  { comap_uniformity := comap_coe_eq_uniformity α
    injective := separated_pureCauchy_injective }

theorem coe_injective [T0Space α] : Function.Injective ((↑) : α → Completion α) :=
  IsUniformEmbedding.injective (isUniformEmbedding_coe _)

variable {α}

@[simp]
lemma coe_inj [T0Space α] {a b : α} : (a : Completion α) = b ↔ a = b :=
  (coe_injective _).eq_iff

theorem isDenseInducing_coe : IsDenseInducing ((↑) : α → Completion α) :=
  { (isUniformInducing_coe α).isInducing with dense := denseRange_coe }

/-- The uniform bijection between a complete space and its uniform completion. -/
def UniformCompletion.completeEquivSelf [CompleteSpace α] [T0Space α] : Completion α ≃ᵤ α :=
  AbstractCompletion.compareEquiv Completion.cPkg AbstractCompletion.ofComplete

open TopologicalSpace

instance separableSpace_completion [SeparableSpace α] : SeparableSpace (Completion α) :=
  Completion.isDenseInducing_coe.separableSpace

theorem isDenseEmbedding_coe [T0Space α] : IsDenseEmbedding ((↑) : α → Completion α) :=
  { isDenseInducing_coe with injective := separated_pureCauchy_injective }

theorem denseRange_coe₂ :
    DenseRange fun x : α × β => ((x.1 : Completion α), (x.2 : Completion β)) :=
  denseRange_coe.prodMap denseRange_coe

theorem denseRange_coe₃ :
    DenseRange fun x : α × β × γ =>
      ((x.1 : Completion α), ((x.2.1 : Completion β), (x.2.2 : Completion γ))) :=
  denseRange_coe.prodMap denseRange_coe₂

@[elab_as_elim]
theorem induction_on {p : Completion α → Prop} (a : Completion α) (hp : IsClosed { a | p a })
    (ih : ∀ a : α, p a) : p a :=
  isClosed_property denseRange_coe hp ih a

@[elab_as_elim]
theorem induction_on₂ {p : Completion α → Completion β → Prop} (a : Completion α) (b : Completion β)
    (hp : IsClosed { x : Completion α × Completion β | p x.1 x.2 })
    (ih : ∀ (a : α) (b : β), p a b) : p a b :=
  have : ∀ x : Completion α × Completion β, p x.1 x.2 :=
    isClosed_property denseRange_coe₂ hp fun ⟨a, b⟩ => ih a b
  this (a, b)

@[elab_as_elim]
theorem induction_on₃ {p : Completion α → Completion β → Completion γ → Prop} (a : Completion α)
    (b : Completion β) (c : Completion γ)
    (hp : IsClosed { x : Completion α × Completion β × Completion γ | p x.1 x.2.1 x.2.2 })
    (ih : ∀ (a : α) (b : β) (c : γ), p a b c) : p a b c :=
  have : ∀ x : Completion α × Completion β × Completion γ, p x.1 x.2.1 x.2.2 :=
    isClosed_property denseRange_coe₃ hp fun ⟨a, b, c⟩ => ih a b c
  this (a, b, c)

theorem ext {Y : Type*} [TopologicalSpace Y] [T2Space Y] {f g : Completion α → Y}
    (hf : Continuous f) (hg : Continuous g) (h : ∀ a : α, f a = g a) : f = g :=
  cPkg.funext hf hg h

theorem ext' {Y : Type*} [TopologicalSpace Y] [T2Space Y] {f g : Completion α → Y}
    (hf : Continuous f) (hg : Continuous g) (h : ∀ a : α, f a = g a) (a : Completion α) :
    f a = g a :=
  congr_fun (ext hf hg h) a

section Extension

variable {f : α → β}

/--
The extension of a uniformly continuous map `f : α → β` into a complete separated uniform space to
the completion of `α`: the unique uniformly continuous map that agrees with `f` on `α`
(`UniformSpace.Completion.extension_coe`, `UniformSpace.Completion.extension_unique`).
Completeness of `β` is a sufficient condition for the limits that define it.  When `β` is not
separated, `Completion.extension (SeparationQuotient.mk ∘ f)` extends `f` into the separation
quotient of `β`, which is complete when `β` is.
-/
protected def extension [CompleteSpace β] [T0Space β] (f : α → β)
    (hf : UniformContinuous f := by fun_prop_default) : Completion α → β :=
  cPkg.extend f hf

variable [CompleteSpace β] [T0Space β]

@[fun_prop]
theorem uniformContinuous_extension (hf : UniformContinuous f) :
    UniformContinuous (Completion.extension f hf) :=
  cPkg.uniformContinuous_extend hf

@[continuity, fun_prop]
theorem continuous_extension (hf : UniformContinuous f) :
    Continuous (Completion.extension f hf) :=
  cPkg.continuous_extend hf

theorem extension_coe (hf : UniformContinuous f) (a : α) : (Completion.extension f hf) a = f a :=
  cPkg.extend_coe hf a

lemma isUniformInducing_extension (h : IsUniformInducing f) :
    IsUniformInducing (Completion.extension f h.uniformContinuous) :=
  cPkg.isUniformInducing_extend h

theorem extension_unique (hf : UniformContinuous f) {g : Completion α → β}
    (hg : UniformContinuous g) (h : ∀ a : α, f a = g (a : Completion α)) :
    Completion.extension f hf = g :=
  cPkg.extend_unique hf hg h

@[simp]
theorem extension_comp_coe {f : Completion α → β} (hf : UniformContinuous f) :
    Completion.extension (f ∘ (↑)) (hf.comp (uniformContinuous_coe α)) = f :=
  cPkg.extend_comp_coe hf

end Extension

/-- A map into a complete separated space extends continuously to the completion exactly when it is
Cauchy continuous.  This is the domain of the operations of `Completion α`
(`Mathlib/Topology/Algebra/GroupCompletion.lean`, `Mathlib/Topology/Algebra/UniformRing.lean`). -/
theorem cauchyContinuous_iff_exists_continuous_extension [CompleteSpace β] [T0Space β]
    {f : α → β} :
    CauchyContinuous f ↔ ∃ g : Completion α → β, Continuous g ∧ ∀ a : α, g a = f a := by
  refine ⟨fun hf ↦ ⟨isDenseInducing_coe.extend f, ?_, fun a ↦ ?_⟩, ?_⟩
  · exact hf.continuous_extend (isUniformInducing_coe α) denseRange_coe
  · exact hf.extend_eq (isUniformInducing_coe α) denseRange_coe a
  · rintro ⟨g, hg, hgf⟩
    have : f = g ∘ ((↑) : α → Completion α) := funext fun a ↦ (hgf a).symm
    rw [this]
    exact hg.cauchyContinuous_comp (uniformContinuous_coe α).cauchyContinuous

section Map

variable {f : α → β}

/-- Completion functor acting on uniformly continuous maps -/
protected def map (f : α → β) (hf : UniformContinuous f := by fun_prop_default) :
    Completion α → Completion β :=
  cPkg.map cPkg f hf

@[fun_prop]
theorem uniformContinuous_map (hf : UniformContinuous f) :
    UniformContinuous (Completion.map f hf) :=
  cPkg.uniformContinuous_map cPkg hf

@[continuity, fun_prop]
theorem continuous_map (hf : UniformContinuous f) : Continuous (Completion.map f hf) :=
  cPkg.continuous_map cPkg hf

theorem map_coe (hf : UniformContinuous f) (a : α) : (Completion.map f hf) a = f a :=
  cPkg.map_coe cPkg hf a

theorem map_unique (hf : UniformContinuous f) {g : Completion α → Completion β}
    (hg : UniformContinuous g) (h : ∀ a : α, ↑(f a) = g a) : Completion.map f hf = g :=
  cPkg.map_unique cPkg hf hg h

/-- The map induced on completions depends only on the function, not on the proof of its uniform
continuity. -/
theorem map_congr {f g : α → β} (h : f = g) {hf : UniformContinuous f}
    {hg : UniformContinuous g} : Completion.map f hf = Completion.map g hg := by
  subst h
  rfl

@[simp]
theorem map_id : Completion.map (@id α) uniformContinuous_id = id :=
  cPkg.map_id

theorem extension_map [CompleteSpace γ] [T0Space γ] {f : β → γ} {g : α → β}
    (hf : UniformContinuous f) (hg : UniformContinuous g) :
    Completion.extension f hf ∘ Completion.map g hg = Completion.extension (f ∘ g) (hf.comp hg) :=
  Completion.ext ((continuous_extension hf).comp (continuous_map hg))
    (continuous_extension _) <| by
    simp [map_coe, extension_coe]

set_option backward.isDefEq.respectTransparency false in
theorem map_comp {g : β → γ} {f : α → β} (hg : UniformContinuous g) (hf : UniformContinuous f) :
    Completion.map g hg ∘ Completion.map f hf = Completion.map (g ∘ f) (hg.comp hf) :=
  extension_map ((uniformContinuous_coe _).comp hg) hf

/-- The uniform isomorphism between two completions of isomorphic uniform spaces. -/
def mapEquiv (e : α ≃ᵤ β) : Completion α ≃ᵤ Completion β := cPkg.mapEquiv cPkg e

@[simp]
theorem mapEquiv_symm (e : α ≃ᵤ β) : (mapEquiv e).symm = mapEquiv e.symm :=
  cPkg.mapEquiv_symm cPkg e

@[simp]
theorem mapEquiv_coe (e : α ≃ᵤ β) (a : α) : mapEquiv e a = (e a) := cPkg.mapEquiv_coe cPkg e a

end Map

/- In this section we construct isomorphisms between the completion of a uniform space and the
completion of its separation quotient -/
section SeparationQuotientCompletion

open SeparationQuotient in
/-- The isomorphism between the completion of a uniform space and the completion of its separation
quotient. -/
def completionSeparationQuotientEquiv (α : Type u) [UniformSpace α] :
    Completion (SeparationQuotient α) ≃ Completion α := by
  refine ⟨Completion.extension (lift' ((↑) : α → Completion α)) (uniformContinuous_lift' _),
    Completion.map SeparationQuotient.mk, fun a ↦ ?_, fun a ↦ ?_⟩
  · refine induction_on a (isClosed_eq ((continuous_map uniformContinuous_mk).comp
      (continuous_extension (uniformContinuous_lift' _))) continuous_id) ?_
    refine SeparationQuotient.surjective_mk.forall.2 fun a ↦ ?_
    rw [extension_coe (uniformContinuous_lift' _), lift'_mk (uniformContinuous_coe α),
      map_coe uniformContinuous_mk]
  · refine induction_on a (isClosed_eq ((continuous_extension (uniformContinuous_lift' _)).comp
      (continuous_map uniformContinuous_mk)) continuous_id) fun a ↦ ?_
    rw [map_coe uniformContinuous_mk, extension_coe (uniformContinuous_lift' _),
      lift'_mk (uniformContinuous_coe _)]

@[fun_prop]
theorem uniformContinuous_completionSeparationQuotientEquiv :
    UniformContinuous (completionSeparationQuotientEquiv α) :=
  uniformContinuous_extension (SeparationQuotient.uniformContinuous_lift' _)

@[fun_prop]
theorem uniformContinuous_completionSeparationQuotientEquiv_symm :
    UniformContinuous (completionSeparationQuotientEquiv α).symm :=
  uniformContinuous_map SeparationQuotient.uniformContinuous_mk

end SeparationQuotientCompletion

section Extension₂

/-- Extend a uniformly continuous two variable map to the Hausdorff completions. -/
protected def extension₂ [CompleteSpace γ] [T0Space γ] (f : α → β → γ)
    (hf : UniformContinuous₂ f) : Completion α → Completion β → γ :=
  cPkg.extend₂ cPkg f hf

variable [CompleteSpace γ] [T0Space γ] {f : α → β → γ}

theorem extension₂_coe_coe (hf : UniformContinuous₂ f) (a : α) (b : β) :
    Completion.extension₂ f hf a b = f a b :=
  cPkg.extension₂_coe_coe cPkg hf a b

@[fun_prop]
theorem uniformContinuous_extension₂ (hf : UniformContinuous₂ f) :
    UniformContinuous₂ (Completion.extension₂ f hf) :=
  cPkg.uniformContinuous_extension₂ cPkg hf

end Extension₂

section Map₂

/-- Lift a uniformly continuous two variable map to the Hausdorff completions. -/
protected def map₂ (f : α → β → γ) (hf : UniformContinuous₂ f) :
    Completion α → Completion β → Completion γ :=
  cPkg.map₂ cPkg cPkg f hf

@[fun_prop]
theorem uniformContinuous_map₂ {f : α → β → γ} (hf : UniformContinuous₂ f) :
    UniformContinuous₂ (Completion.map₂ f hf) :=
  cPkg.uniformContinuous_map₂ cPkg cPkg hf

theorem continuous_map₂ {δ} [TopologicalSpace δ] {f : α → β → γ} (hf : UniformContinuous₂ f)
    {a : δ → Completion α} {b : δ → Completion β} (ha : Continuous a) (hb : Continuous b) :
    Continuous fun d : δ => Completion.map₂ f hf (a d) (b d) :=
  cPkg.continuous_map₂ cPkg cPkg hf ha hb

theorem map₂_coe_coe (a : α) (b : β) (f : α → β → γ) (hf : UniformContinuous₂ f) :
    Completion.map₂ f hf (a : Completion α) (b : Completion β) = f a b :=
  cPkg.map₂_coe_coe cPkg cPkg a b f hf

end Map₂

end Completion

end UniformSpace
