/-
Copyright (c) 2023 Rémy Degenne. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Rémy Degenne
-/
module

public import Mathlib.MeasureTheory.Constructions.BorelSpace.FiniteOnIic
public import Mathlib.MeasureTheory.Measure.Real
public import Mathlib.MeasureTheory.Measure.Stieltjes
public import Mathlib.Tactic.CrossRefAttribute
public import Mathlib.Topology.UnitInterval

/-!
# Cumulative distribution function of a measure on `ℝ`

The cumulative distribution function (cdf) of a measure `μ` on `ℝ` that is finite on every ray
`Iic x` is the real function `x ↦ μ.real (Iic x)`. It is a monotone, right continuous function
with limit 0 at -∞, and it is the unique such function that generates `μ`: the measure associated
to the Stieltjes function `cdf μ` is `μ`. Conversely, every Stieltjes function with limit 0 at -∞
is the cdf of its associated measure. The cdf of a finite measure has limit `μ.real univ` at +∞,
and the cdf of a probability measure is the cumulative distribution function of probability
theory, with limit 1 at +∞.

## Main definitions

* `ProbabilityTheory.cdf μ`: cumulative distribution function `x ↦ μ.real (Iic x)` of a measure
  `μ : Measure ℝ` that is finite on every ray `Iic x`, as a Stieltjes function.

## Main statements

* `ProbabilityTheory.ofReal_cdf`: `ENNReal.ofReal (cdf μ x) = μ (Iic x)`.
* `ProbabilityTheory.measure_cdf`: the measure associated to the Stieltjes function `cdf μ` is `μ`.
* `ProbabilityTheory.cdf_measure_stieltjesFunction`: a Stieltjes function with limit 0 at -∞ is the
  cdf of its associated measure.
* `MeasureTheory.Measure.eq_of_cdf`: two measures that are finite on every ray `Iic x` and have the
  same cdf are equal.

## Implementation notes

The domain of `cdf` is the class `IsFiniteMeasureOnIic` of measures that are finite on every ray
`Iic x`. These are exactly the measures generated by a Stieltjes function with a finite limit at
-∞, and the cdf is then the unique Stieltjes function with limit 0 at -∞ that generates the
measure ([siegrist_random], §3.9). The domain contains infinite measures such as the restriction
of Lebesgue measure to `[0, ∞)`; for a finite measure, the cdf is the distribution function of
[folland1999], §1.5. A locally finite measure in which some ray `Iic x` has infinite measure, such
as Lebesgue measure, determines its Stieltjes functions only up to an additive constant, and none
of them tends to 0 at -∞. Statements that need a finite or a probability measure, such as
`ProbabilityTheory.tendsto_cdf_atTop`, assume it.

## References

* [G. B. Folland, *Real analysis: modern techniques and their applications*][folland1999]
* [K. Siegrist, *Probability, Mathematical Statistics, and Stochastic Processes*][siegrist_random]

## TODO

The definition could be extended to `ℝⁿ`.
-/

@[expose] public section

open MeasureTheory Measure Set Filter

open scoped ENNReal Topology

namespace ProbabilityTheory

/-- Cumulative distribution function `x ↦ μ.real (Iic x)` of a measure `μ` on `ℝ` that is finite on
every ray `Iic x`, as a Stieltjes function. It is the unique Stieltjes function with limit 0 at -∞
that generates `μ`. For a probability measure, this is the cumulative distribution function of
probability theory. -/
@[wikidata Q386228]
noncomputable
def cdf (μ : Measure ℝ) [IsFiniteMeasureOnIic μ] : StieltjesFunction ℝ where
  toFun x := μ.real (Iic x)
  mono' _ _ hxy := measureReal_mono (Iic_subset_Iic.2 hxy)
  right_continuous' x := by
    rw [← continuousWithinAt_Ioi_iff_Ici]
    have h_inter : ⋂ y > x, Iic y = Iic x := by
      ext z
      simp only [mem_iInter, mem_Iic]
      exact ⟨le_of_forall_gt_imp_ge_of_dense, fun hz y hy ↦ hz.trans hy.le⟩
    have h := tendsto_measure_biInter_gt (μ := μ) (s := Iic) (a := x)
      (fun _ _ ↦ measurableSet_Iic.nullMeasurableSet) (fun _ _ _ hyz ↦ Iic_subset_Iic.2 hyz)
      ⟨x + 1, lt_add_one x, measure_Iic_ne_top μ _⟩
    rw [h_inter] at h
    exact (ENNReal.tendsto_toReal (measure_Iic_ne_top μ x)).comp h

section ExplicitMeasureArg
variable (μ : Measure ℝ) [IsFiniteMeasureOnIic μ]

/-- The cdf is non-negative. -/
lemma cdf_nonneg (x : ℝ) : 0 ≤ cdf μ x := measureReal_nonneg

/-- The cdf is monotone. -/
lemma monotone_cdf : Monotone (cdf μ) := (cdf μ).mono

/-- The cdf tends to 0 at -∞. -/
lemma tendsto_cdf_atBot : Tendsto (cdf μ) atBot (𝓝 0) := by
  have h_inter : ⋂ x : ℝ, Iic x = ∅ := by
    ext y
    simp only [mem_iInter, mem_Iic, mem_empty_iff_false, iff_false, not_forall, not_le]
    exact ⟨y - 1, sub_one_lt y⟩
  have h := tendsto_measure_iInter_atBot (μ := μ) (s := Iic)
    (fun _ ↦ measurableSet_Iic.nullMeasurableSet) (fun _ _ hxy ↦ Iic_subset_Iic.2 hxy)
    ⟨0, measure_Iic_ne_top μ _⟩
  rw [h_inter, measure_empty] at h
  exact (ENNReal.tendsto_toReal ENNReal.zero_ne_top).comp h

lemma ofReal_cdf (x : ℝ) : ENNReal.ofReal (cdf μ x) = μ (Iic x) := ofReal_measureReal

lemma cdf_eq_real (x : ℝ) : cdf μ x = μ.real (Iic x) := rfl

/-- The measure associated to the cdf of a measure is the same measure. -/
lemma measure_cdf : (cdf μ).measure = μ := by
  refine ext_of_Ioc' (cdf μ).measure μ (fun a b _ ↦ by simp) (fun a b hab ↦ ?_)
  have h_Ioc : μ (Ioc a b) ≠ ∞ :=
    measure_ne_top_of_subset Ioc_subset_Iic_self (measure_Iic_ne_top μ b)
  have h : μ.real (Iic b) = μ.real (Iic a) + μ.real (Ioc a b) := by
    rw [← Iic_union_Ioc_eq_Iic hab.le,
      measureReal_union (Iic_disjoint_Ioc le_rfl) measurableSet_Ioc (h₂ := h_Ioc)]
  rw [StieltjesFunction.measure_Ioc, cdf_eq_real, cdf_eq_real, h, add_sub_cancel_left,
    ofReal_measureReal h_Ioc]

instance instIsFiniteMeasureOnIiccdf : IsFiniteMeasureOnIic (cdf μ).measure := by
  rw [measure_cdf]
  infer_instance

end ExplicitMeasureArg

section FiniteMeasure
variable (μ : Measure ℝ) [IsFiniteMeasure μ]

/-- The cdf of a finite measure is bounded by the total mass. -/
lemma cdf_le_measureReal_univ (x : ℝ) : cdf μ x ≤ μ.real univ :=
  measureReal_mono (subset_univ _)

/-- The cdf of a finite measure tends to the total mass `μ.real univ` at +∞. -/
lemma tendsto_cdf_atTop_measureReal_univ : Tendsto (cdf μ) atTop (𝓝 (μ.real univ)) :=
  (ENNReal.tendsto_toReal (measure_ne_top μ _)).comp (tendsto_measure_Iic_atTop μ)

instance instIsFiniteMeasurecdf : IsFiniteMeasure (cdf μ).measure := by
  rw [measure_cdf]
  infer_instance

end FiniteMeasure

/-- The cdf of a probability measure, or of the zero measure, is lower or equal to 1. -/
lemma cdf_le_one (μ : Measure ℝ) [IsZeroOrProbabilityMeasure μ] (x : ℝ) : cdf μ x ≤ 1 :=
  measureReal_le_one

section ProbabilityMeasure
variable (μ : Measure ℝ) [IsProbabilityMeasure μ]

/-- The cdf of a probability measure tends to 1 at +∞. -/
lemma tendsto_cdf_atTop : Tendsto (cdf μ) atTop (𝓝 1) := by
  simpa using tendsto_cdf_atTop_measureReal_univ μ

instance instIsProbabilityMeasurecdf : IsProbabilityMeasure (cdf μ).measure := by
  rw [measure_cdf]
  infer_instance

end ProbabilityMeasure

/-- The measure associated to a Stieltjes function with a finite limit at -∞ is finite on every
ray `Iic x`. -/
lemma _root_.StieltjesFunction.isFiniteMeasureOnIic (f : StieltjesFunction ℝ) {l : ℝ}
    (hf : Tendsto f atBot (𝓝 l)) : IsFiniteMeasureOnIic f.measure :=
  ⟨fun x ↦ by rw [f.measure_Iic hf]; exact ENNReal.ofReal_lt_top⟩

/-- A Stieltjes function with limit 0 at -∞ is the cdf of its associated measure. -/
lemma cdf_measure_stieltjesFunction (f : StieltjesFunction ℝ) (hf0 : Tendsto f atBot (𝓝 0)) :
    haveI := f.isFiniteMeasureOnIic hf0
    cdf f.measure = f := by
  have := f.isFiniteMeasureOnIic hf0
  exact (cdf f.measure).eq_of_measure_of_tendsto_atBot f (measure_cdf _) (tendsto_cdf_atBot _) hf0

open unitInterval in
lemma unitInterval.cdf_eq_real (μ : Measure I) [IsFiniteMeasure μ] (x : I) :
    cdf (μ.map Subtype.val) x.1 = μ.real (Icc 0 x) := by
  rw [ProbabilityTheory.cdf_eq_real,
    map_measureReal_apply measurable_subtype_coe measurableSet_Iic, subtype_Iic_eq_Icc]

end ProbabilityTheory

open ProbabilityTheory

/-- If two measures on `ℝ` that are finite on every ray `Iic x` have the same cdf, they are
equal. -/
lemma MeasureTheory.Measure.eq_of_cdf (μ ν : Measure ℝ) [IsFiniteMeasureOnIic μ]
    [IsFiniteMeasureOnIic ν] (h : cdf μ = cdf ν) : μ = ν := by
  rw [← measure_cdf μ, ← measure_cdf ν, h]

@[simp] lemma MeasureTheory.Measure.cdf_eq_iff (μ ν : Measure ℝ) [IsFiniteMeasureOnIic μ]
    [IsFiniteMeasureOnIic ν] :
    cdf μ = cdf ν ↔ μ = ν :=
⟨eq_of_cdf μ ν, fun h ↦ by subst ν; rfl⟩
