/-
Copyright (c) 2026 Yi-Jing Tseng. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yi-Jing Tseng
-/
module

public import Mathlib.MeasureTheory.Measure.Typeclasses.Finite

/-!
# Measures that are finite on initial rays

We introduce the typeclass `IsFiniteMeasureOnIic μ` for a measure `μ` on a preorder that is finite
on every initial ray `Iic x`. On `ℝ` these are exactly the measures generated by a right continuous
monotone function with a finite limit at `-∞`; the function `x ↦ μ.real (Iic x)` is then the
unique such function with limit `0` at `-∞` that generates `μ` (see `ProbabilityTheory.cdf`).
Finite measures, such as probability measures, are finite on initial rays; so are infinite
measures such as the restriction of Lebesgue measure to `[0, ∞)`. On a linear order in which
every ray `Ici y` is closed, a measure that is finite on initial rays is locally finite, hence
σ-finite when the topology is second countable.
-/

public section

open Set ENNReal

open scoped NNReal

namespace MeasureTheory

variable {α : Type*} {m0 : SigmaAlgebra α} [Preorder α]

/-- A measure `μ` on a preorder is finite on initial rays if `μ (Iic x) < ∞` for every `x`. -/
class IsFiniteMeasureOnIic (μ : Measure α) : Prop where
  protected measure_Iic_lt_top : ∀ x, μ (Iic x) < ∞

@[simp]
theorem measure_Iic_lt_top (μ : Measure α) [IsFiniteMeasureOnIic μ] (x : α) : μ (Iic x) < ∞ :=
  IsFiniteMeasureOnIic.measure_Iic_lt_top x

@[simp, aesop (rule_sets := [finiteness]) safe apply]
theorem measure_Iic_ne_top (μ : Measure α) [IsFiniteMeasureOnIic μ] (x : α) : μ (Iic x) ≠ ∞ :=
  (measure_Iic_lt_top μ x).ne

-- see Note [lower instance priority]
instance (priority := 100) IsFiniteMeasure.toIsFiniteMeasureOnIic (μ : Measure α)
    [IsFiniteMeasure μ] : IsFiniteMeasureOnIic μ :=
  ⟨fun _ ↦ measure_lt_top μ _⟩

instance isFiniteMeasureOnIic_restrict (μ : Measure α) [IsFiniteMeasureOnIic μ] (s : Set α) :
    IsFiniteMeasureOnIic (μ.restrict s) :=
  ⟨fun x ↦ (Measure.restrict_apply_le _ _).trans_lt (measure_Iic_lt_top μ x)⟩

instance isFiniteMeasureOnIic_add (μ ν : Measure α) [IsFiniteMeasureOnIic μ]
    [IsFiniteMeasureOnIic ν] : IsFiniteMeasureOnIic (μ + ν) :=
  ⟨fun x ↦ by
    rw [Measure.coe_add, Pi.add_apply, ENNReal.add_lt_top]
    exact ⟨measure_Iic_lt_top μ x, measure_Iic_lt_top ν x⟩⟩

instance isFiniteMeasureOnIic_smul_nnreal (μ : Measure α) [IsFiniteMeasureOnIic μ] (c : ℝ≥0) :
    IsFiniteMeasureOnIic (c • μ) :=
  ⟨fun x ↦ ENNReal.mul_lt_top ENNReal.coe_lt_top (measure_Iic_lt_top μ x)⟩

section LinearOrder

variable {β : Type*} {mβ : SigmaAlgebra β} [TopologicalSpace β] [LinearOrder β]
  [ClosedIciTopology β]

/-- A measure that is finite on initial rays, on a linear order in which every ray `Ici y` is
closed, is locally finite: a point lies in an open ray `Iio y` of finite measure, unless it is the
greatest element, whose ray `Iic x` is the whole space. -/
-- see Note [lower instance priority]
instance (priority := 100) IsFiniteMeasureOnIic.toIsLocallyFiniteMeasure (μ : Measure β)
    [IsFiniteMeasureOnIic μ] : IsLocallyFiniteMeasure μ :=
  ⟨fun x ↦ by
    by_cases hx : ∃ y, x < y
    · obtain ⟨y, hxy⟩ := hx
      exact ⟨Iio y, Iio_mem_nhds hxy,
        (measure_mono Iio_subset_Iic_self).trans_lt (measure_Iic_lt_top μ y)⟩
    · simp only [not_exists, not_lt] at hx
      have h : Iic x = univ := eq_univ_of_forall hx
      exact ⟨univ, Filter.univ_mem, h ▸ measure_Iic_lt_top μ x⟩⟩

end LinearOrder

end MeasureTheory
