import Mathlib.Probability.Independence.Conditional
import Mathlib.Probability.Moments.SubGaussian

/-!
# The conditional expectation kernel as an almost-everywhere class

These tests check that `ProbabilityTheory.condExpKernel μ hm` is the `μ.trim hm`-almost-everywhere
class of the kernels that disintegrate the diagonal law, so that no chosen kernel, with its Markov
instance, measurability lemmas, and defining equations, is public; that a finite kernel represents
it exactly when it disintegrates the diagonal law, that a Markov representative exists, and that
every Markov representative computes conditional probabilities; that conditional independence and
the conditionally sub-Gaussian property are decided by any single representative; that, given the
full σ-algebra, the identity kernel represents the class while a kernel that is wrong at an atom
does not; that the class requires the proof that `m` is a sub-σ-algebra and the class of the joint
law of `(ω, ω)`, which instance search supplies for a standard Borel space and a σ-finite trim, such
as Lebesgue measure, for the empty type, and for a finite measure and the σ-algebra generated by one
set.
-/

open MeasureTheory ProbabilityTheory SigmaAlgebra

noncomputable section

/-! ### No chosen conditional expectation kernel is public -/

/-- error: Unknown identifier `ProbabilityTheory.instIsMarkovKernelCondExpKernel` -/
#guard_msgs in
#check ProbabilityTheory.instIsMarkovKernelCondExpKernel

/-- error: Unknown identifier `ProbabilityTheory.condExpKernel_eq` -/
#guard_msgs in
#check ProbabilityTheory.condExpKernel_eq

/-- error: Unknown identifier `ProbabilityTheory.condExpKernel_apply_eq_condDistrib` -/
#guard_msgs in
#check ProbabilityTheory.condExpKernel_apply_eq_condDistrib

/-- error: Unknown identifier `ProbabilityTheory.measurable_condExpKernel` -/
#guard_msgs in
#check ProbabilityTheory.measurable_condExpKernel

/-- error: Unknown identifier `ProbabilityTheory.stronglyMeasurable_condExpKernel` -/
#guard_msgs in
#check ProbabilityTheory.stronglyMeasurable_condExpKernel

/-- error: Unknown identifier `ProbabilityTheory.condExpKernel_ae_eq_condExp'` -/
#guard_msgs in
#check ProbabilityTheory.condExpKernel_ae_eq_condExp'

/-- error: Unknown identifier `ProbabilityTheory.integrable_toReal_condExpKernel` -/
#guard_msgs in
#check ProbabilityTheory.integrable_toReal_condExpKernel

/-- error: Unknown identifier `ProbabilityTheory.condExp_ae_eq_integral_condExpKernel'` -/
#guard_msgs in
#check ProbabilityTheory.condExp_ae_eq_integral_condExpKernel'

/-- error: Unknown constant `MeasureTheory.StronglyMeasurable.integral_condExpKernel` -/
#guard_msgs in
#check MeasureTheory.StronglyMeasurable.integral_condExpKernel

/-- error: Unknown constant `MeasureTheory.StronglyMeasurable.integral_condExpKernel'` -/
#guard_msgs in
#check MeasureTheory.StronglyMeasurable.integral_condExpKernel'

/-- error: Unknown identifier `ProbabilityTheory.hasUniqueCondKernel_map_diag` -/
#guard_msgs in
#check ProbabilityTheory.hasUniqueCondKernel_map_diag

/-- error: Unknown identifier `ProbabilityTheory.exists_aeClass_condExpKernel` -/
#guard_msgs in
#check ProbabilityTheory.exists_aeClass_condExpKernel

/--
error: Unknown identifier `ProbabilityTheory.condIndepFun_iff_condDistrib_prod_ae_eq_prodMkRight`
-/
#guard_msgs in
#check ProbabilityTheory.condIndepFun_iff_condDistrib_prod_ae_eq_prodMkRight

/-! ### Representatives of the class -/

section Class

variable {Ω : Type*} {m m₁ m₂ : SigmaAlgebra Ω} [mΩ : SigmaAlgebra Ω] [StandardBorelSpace Ω]
  {μ : Measure Ω} [IsFiniteMeasure μ]

example (hm : m ≤ mΩ) : @Kernel.AEClass Ω (ae (μ.trim hm)) Ω m mΩ :=
  condExpKernel μ hm

example (hm : m ≤ mΩ) : ∃ η : @Kernel Ω Ω m mΩ, IsMarkovKernel η ∧ η ∈ condExpKernel μ hm :=
  exists_isMarkovKernel_mem_condExpKernel μ hm

-- A finite kernel represents the class exactly when it disintegrates the diagonal law.
example (hm : m ≤ mΩ) (η : @Kernel Ω Ω m mΩ) [IsFiniteKernel η] :
    η ∈ condExpKernel μ hm ↔
      (μ.trim hm) ⊗ₘ η
        = @Measure.map Ω (Ω × Ω) mΩ (m.prod mΩ) Function.diag μ (aemeasurable_diag_of_le μ hm) :=
  mem_condExpKernel_iff

-- Every Markov representative computes conditional probabilities and integrates back to `μ`.
example (hm : m ≤ mΩ) {η : @Kernel Ω Ω m mΩ} [IsMarkovKernel η] (hη : η ∈ condExpKernel μ hm)
    {s : Set Ω} (hs : MeasurableSet s) :
    (fun ω ↦ (η ω).real s) =ᵐ[μ] μ⟦s | m⟧ :=
  condExpKernel_ae_eq_condExp hη hs

-- Every representative integrates back to `μ`.
example (hm : m ≤ mΩ) {η : @Kernel Ω Ω m mΩ} (hη : η ∈ condExpKernel μ hm) :
    η ∘ₘ μ.trim hm = μ :=
  condExpKernel_comp_trim hη

example (hm : m ≤ mΩ) {η : @Kernel Ω Ω m mΩ} (hη : η ∈ condExpKernel μ hm) :
    (μ.trim hm).HasCompProd η :=
  hasCompProd_trim_of_mem_condExpKernel hη

-- A Markov kernel represents the class exactly when it disintegrates the diagonal law.
example (hm : m ≤ mΩ) (η : @Kernel Ω Ω m mΩ) [IsMarkovKernel η] :
    η ∈ condExpKernel μ hm ↔ (μ.trim hm) ⊗ₘ η = condExpJointLaw μ hm :=
  mem_condExpKernel_iff_of_isMarkovKernel

-- Conditional independence and the conditionally sub-Gaussian property are decided by any single
-- representative.
example (hm : m ≤ mΩ) {η : @Kernel Ω Ω m mΩ}
    (hη : η ∈ condExpKernel μ hm) :
    CondIndep m m₁ m₂ hm μ ↔ Kernel.Indep m₁ m₂ η (μ.trim hm) :=
  condIndep_iff_of_mem hη

example (hm : m ≤ mΩ) {η η' : @Kernel Ω Ω m mΩ}
    (hη : η ∈ condExpKernel μ hm) (hη' : η' ∈ condExpKernel μ hm) :
    Kernel.Indep m₁ m₂ η (μ.trim hm) ↔ Kernel.Indep m₁ m₂ η' (μ.trim hm) :=
  (condIndep_iff_of_mem hη).symm.trans (condIndep_iff_of_mem hη')

example (hm : m ≤ mΩ) {X : Ω → ℝ} {c : NNReal} {η : @Kernel Ω Ω m mΩ}
    (hη : η ∈ condExpKernel μ hm) :
    HasCondSubgaussianMGF m hm X c μ ↔ Kernel.HasSubgaussianMGF X c η (μ.trim hm) :=
  hasCondSubgaussianMGF_iff_of_mem hη

end Class

/-! ### Conditional independence and conditional distributions -/

section CondDistrib

variable {Ω β β' γ : Type*} [SigmaAlgebra Ω] [StandardBorelSpace Ω] [SigmaAlgebra β]
  [StandardBorelSpace β] [Nonempty β] [SigmaAlgebra β'] [StandardBorelSpace β'] [Nonempty β']
  [SigmaAlgebra γ] {μ : Measure Ω} [IsFiniteMeasure μ] {f : Ω → β} {g : Ω → β'} {k : Ω → γ}

-- `g` is conditionally independent of `f` given `k` exactly when a Markov representative of the
-- conditional distribution of `f` given `k`, viewed as a kernel that ignores `g`, represents the
-- conditional distribution of `f` given `(k, g)`.
example (hf : Measurable f) (hg : Measurable g) (hk : Measurable k) {η : Kernel γ β}
    [IsMarkovKernel η] (hη : η ∈ condDistrib f k μ) :
    g ⟂ᵢ[k, hk; μ] f ↔ η.prodMkRight β' ∈ condDistrib f (fun ω ↦ (k ω, g ω)) μ :=
  condIndepFun_iff_prodMkRight_mem_condDistrib hf hg hk hη

end CondDistrib

/-! ### Conditioning on the full σ-algebra -/

-- Given the full σ-algebra, the identity kernel represents the class, and the constant kernel
-- `dirac 1`, which is wrong at the atom of `dirac 0`, does not.
theorem id_mem_condExpKernel_dirac : Kernel.id ∈ condExpKernel (Measure.dirac (0 : ℝ)) le_rfl := by
  rw [mem_condExpKernel_iff, trim_eq_self, Measure.compProd_id_eq_copy_comp]
  exact Measure.deterministic_comp_eq_map _

example : Kernel.const ℝ (Measure.dirac 1) ∉ condExpKernel (Measure.dirac (0 : ℝ)) le_rfl := by
  intro h
  have h' := Kernel.AEClass.eventuallyEq_of_mem h id_mem_condExpKernel_dirac
  rw [trim_eq_self, Filter.EventuallyEq, ae_dirac_eq, Filter.eventually_pure] at h'
  have h1 := congrArg (fun ν : Measure ℝ ↦ ν {0}) h'
  simp [Kernel.const_apply, Kernel.id_apply, Measure.dirac_apply'] at h1

/-! ### The class requires a sub-σ-algebra and the class of the joint law -/

-- The sub-σ-algebra is given by the proof that it is one: the former call with the σ-algebra
-- itself is rejected.
set_option pp.mvars false in
/--
error: Application type mismatch: The argument
  ⊥
has type
  SigmaAlgebra ℝ
of sort `Type` but is expected to have type
  ?_ ≤ Real.sigmaAlgebra
of sort `Prop` in the application
  @condExpKernel ℝ ?_ Real.sigmaAlgebra (Measure.dirac 0) ⊥
-/
#guard_msgs in
example : True :=
  let _c := condExpKernel (Measure.dirac (0 : ℝ)) (⊥ : SigmaAlgebra ℝ)
  trivial

-- Lebesgue measure on `ℝ` has no conditional expectation kernel given the trivial σ-algebra: a
-- kernel from `(ℝ, ⊥)` is constant, and infinity times the mass that it gives `[0, 1]` is never
-- `1`.
/--
error: failed to synthesize instance of type class
  (condExpJointLaw ℙ ⋯).HasUniqueCondKernel

Hint: Type class instance resolution failures can be inspected with the `set_option trace.Meta.synthInstance true` command.
-/
#guard_msgs in
example : True :=
  let _c := condExpKernel (volume : Measure ℝ) bot_le
  trivial

-- Given the whole σ-algebra, every measure on a countably generated space has a conditional
-- expectation kernel, which the identity kernel represents: counting measure on `ℝ`, whose trim is
-- not σ-finite.
theorem id_mem_condExpKernel_count :
    (Kernel.id : Kernel ℝ ℝ) ∈ condExpKernel (Measure.count : Measure ℝ) le_rfl := by
  rw [mem_condExpKernel_iff_of_isMarkovKernel, trim_eq_self, Measure.compProd_id_eq_copy_comp]
  exact Measure.deterministic_comp_eq_map _

-- The measurability and integrability statements hold for every measure and representative.
example {f : ℝ → ℝ} (hf : Integrable f (Measure.count : Measure ℝ)) :
    Integrable (fun ω ↦ ∫ y, f y ∂(Kernel.id : Kernel ℝ ℝ) ω) Measure.count :=
  hf.integral_condExpKernel id_mem_condExpKernel_count

example {f : ℝ → ℝ} (hf : AEStronglyMeasurable f (Measure.count : Measure ℝ)) :
    AEStronglyMeasurable (fun ω ↦ ∫ y, f y ∂(Kernel.id : Kernel ℝ ℝ) ω) Measure.count :=
  hf.integral_condExpKernel id_mem_condExpKernel_count

/-! ### Measures that are not finite -/

-- The class of the joint law of `(ω, ω)` needs only a σ-finite trim: Lebesgue measure on `ℝ`.
example : Kernel.AEClass (ae ((volume : Measure ℝ).trim le_rfl)) ℝ :=
  condExpKernel volume le_rfl

example {Ω : Type*} {m : SigmaAlgebra Ω} [mΩ : SigmaAlgebra Ω] [StandardBorelSpace Ω]
    {μ : Measure Ω} (hm : m ≤ mΩ) [SigmaFinite (μ.trim hm)] :
    (condExpJointLaw μ hm).HasUniqueCondKernel :=
  inferInstance

-- The identity kernel represents the class for Lebesgue measure and the full σ-algebra, and every
-- Markov representative computes conditional expectations of integrable functions.
example : Kernel.id ∈ condExpKernel (volume : Measure ℝ) le_rfl := by
  rw [mem_condExpKernel_iff, trim_eq_self, Measure.compProd_id_eq_copy_comp]
  exact Measure.deterministic_comp_eq_map _

example {Ω : Type*} {m : SigmaAlgebra Ω} [mΩ : SigmaAlgebra Ω] [StandardBorelSpace Ω]
    {μ : Measure Ω} (hm : m ≤ mΩ) [SigmaFinite (μ.trim hm)] {η : @Kernel Ω Ω m mΩ}
    [IsMarkovKernel η] (hη : η ∈ condExpKernel μ hm) {f : Ω → ℝ} (hf : Integrable f μ) :
    μ[f | m] =ᵐ[μ] fun ω ↦ ∫ y, f y ∂η ω :=
  condExp_ae_eq_integral_condExpKernel hη hf

-- A measurable set of infinite measure needs its finiteness as a hypothesis.
example {Ω : Type*} {m : SigmaAlgebra Ω} [mΩ : SigmaAlgebra Ω] [StandardBorelSpace Ω]
    {μ : Measure Ω} (hm : m ≤ mΩ) [SigmaFinite (μ.trim hm)] {η : @Kernel Ω Ω m mΩ}
    [IsMarkovKernel η] (hη : η ∈ condExpKernel μ hm) {s : Set Ω} (hs : MeasurableSet s)
    (hμs : μ s ≠ ⊤) :
    (fun ω ↦ (η ω).real s) =ᵐ[μ] μ⟦s | m⟧ :=
  condExpKernel_ae_eq_condExp hη hs hμs

-- The representatives are those of the conditional distribution of the identity given the
-- identity, for every kernel.
example {Ω : Type*} {m : SigmaAlgebra Ω} [mΩ : SigmaAlgebra Ω] [StandardBorelSpace Ω]
    {μ : Measure Ω} (hm : m ≤ mΩ) [SigmaFinite (μ.trim hm)] (η : @Kernel Ω Ω m mΩ) :
    η ∈ condExpKernel μ hm ↔
      η ∈ @condDistrib Ω Ω Ω mΩ mΩ m id id μ (aemeasurable_diag_of_le μ hm)
        (inferInstance : (condExpJointLaw μ hm).HasUniqueCondKernel) :=
  mem_condExpKernel_iff_mem_condDistrib

-- The empty type.
example (μ : Measure Empty) : (condExpJointLaw μ le_rfl).HasUniqueCondKernel :=
  inferInstance

-- Conditioning on a set of positive finite measure needs only the class of the joint law, and every
-- representative is the conditional measure at every point of the set.
example {Ω : Type*} [mΩ : SigmaAlgebra Ω] {μ : Measure Ω} {s : Set Ω} (hs : MeasurableSet s)
    [(condExpJointLaw μ (generateFrom_singleton_le hs)).HasUniqueCondKernel] (hμs₀ : μ s ≠ 0)
    (hμs : μ s ≠ ⊤) {ξ : @Kernel Ω Ω (generateFrom {s}) mΩ}
    (hξ : ξ ∈ condExpKernel μ (generateFrom_singleton_le hs)) :
    ∀ ω ∈ s, ξ ω = μ[|s] :=
  condExpKernel_singleton_eq_cond hs hμs₀ hξ hμs

-- For a finite measure, instance search supplies the class for the σ-algebra generated by one
-- set, on every space, and the default argument `finiteness` supplies the finiteness of the set.
example {Ω : Type*} [mΩ : SigmaAlgebra Ω] {μ : Measure Ω} [IsFiniteMeasure μ] {s : Set Ω}
    (hs : MeasurableSet s) :
    (condExpJointLaw μ (generateFrom_singleton_le hs)).HasUniqueCondKernel :=
  inferInstance

example {Ω : Type*} [mΩ : SigmaAlgebra Ω] {μ : Measure Ω} [IsFiniteMeasure μ] {s : Set Ω}
    (hs : MeasurableSet s) (hμs₀ : μ s ≠ 0) {ξ : @Kernel Ω Ω (generateFrom {s}) mΩ}
    (hξ : ξ ∈ condExpKernel μ (generateFrom_singleton_le hs)) :
    ∀ ω ∈ s, ξ ω = μ[|s] :=
  condExpKernel_singleton_eq_cond hs hμs₀ hξ

-- Lebesgue measure is not finite, so instance search does not supply the class for the σ-algebra
-- generated by `[0, 1]`: for a σ-finite measure, the class holds for the σ-algebra generated by
-- one set only when the measure is finite.
/--
error: failed to synthesize instance of type class
  (condExpJointLaw ℙ ⋯).HasUniqueCondKernel

Hint: Type class instance resolution failures can be inspected with the `set_option trace.Meta.synthInstance true` command.
-/
#guard_msgs in
example : (condExpJointLaw (volume : Measure ℝ)
    (generateFrom_singleton_le (measurableSet_Icc (a := (0 : ℝ)) (b := 1)))).HasUniqueCondKernel :=
  inferInstance

-- The joint law of `(ω, ω)` on rectangles.
example {Ω : Type*} {m : SigmaAlgebra Ω} [mΩ : SigmaAlgebra Ω] {μ : Measure Ω} (hm : m ≤ mΩ)
    {A B : Set Ω} (hA : A ∈ m) (hB : MeasurableSet B) :
    condExpJointLaw μ hm (A ×ˢ B) = μ (A ∩ B) :=
  condExpJointLaw_apply_prod hA hB

/-- error: Unknown identifier `ProbabilityTheory.condExpKernel_singleton_ae_eq_cond` -/
#guard_msgs in
#check ProbabilityTheory.condExpKernel_singleton_ae_eq_cond

-- A representative of the conditional distribution given `Y` and one of the conditional
-- expectation kernel given `mγ.comap Y` agree on every measurable set, for every measure with the
-- classes of the two joint laws, without a σ-finite law of `Y`.
example {Ω β γ : Type*} [mΩ : SigmaAlgebra Ω] {mβ : SigmaAlgebra β} {mγ : SigmaAlgebra γ}
    {μ : Measure Ω} {X : Ω → β} {Y : Ω → γ} (hX : Measurable X) (hY : Measurable Y)
    {s : Set β} (hs : MeasurableSet s)
    [(μ.map (fun a ↦ (Y a, X a)) (hY.aemeasurable.prodMk hX.aemeasurable)).HasUniqueCondKernel]
    {η₁ : Kernel γ β} (hη₁ : η₁ ∈ condDistrib X Y μ (hY.aemeasurable.prodMk hX.aemeasurable))
    [(condExpJointLaw μ hY.comap_le).HasUniqueCondKernel]
    {η₂ : @Kernel Ω Ω (mγ.comap Y) mΩ} (hη₂ : η₂ ∈ condExpKernel μ hY.comap_le) :
    (fun a ↦ η₁ (Y a) s) =ᵐ[μ] fun a ↦ η₂.map X hX a s :=
  condDistrib_apply_ae_eq_condExpKernel_map hX hY hs hη₁ hη₂

end
