import Mathlib.FieldTheory.RatFunc.IntermediateField

/-!
# `K⟮X⟯` is the field generated by `X`

The field of rational functions over `K` is written `RatFunc K`. The brackets `F⟮x₁, ..., xₙ⟯` are
only `IntermediateField.adjoin`, also for the variable `X`, so `K⟮X⟯` is the subfield of
`RatFunc K` generated by `X`, which is the whole field.
-/

open IntermediateField RatFunc

variable (K : Type*) [Field K]

/-- info: K⟮X⟯ : IntermediateField K (RatFunc K) -/
#guard_msgs in
#check K⟮(X : RatFunc K)⟯

example : K⟮(X : RatFunc K)⟯ = ⊤ := adjoin_X

example (f : RatFunc K) :
    Module.finrank K⟮f⟯ (RatFunc K) = max f.num.natDegree f.denom.natDegree :=
  finrank_eq_max_natDegree f
