/-
Copyright (c) 2026 Thomas Browning. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Thomas Browning
-/
module

public import Mathlib.Algebra.Polynomial.Splits
public import Mathlib.GroupTheory.Perm.ClosureSwap
public import Mathlib.RingTheory.Ideal.Quotient.Operations
public import Mathlib.RingTheory.Spectrum.Maximal.Defs

/-!
# Galois Groups of Morse Polynomials

This file proves that Morse polynomials have Galois group `S_n`. A Morse polynomial is a
polynomial whose roots have at most one collision modulo each maximal ideal.

## Main results

- `Polynomial.surjective_toPermHom_of_iSup_inertia_eq_top`: If the roots of `f` in `S` have at most
  one collision modulo each maximal ideal `m`, and if a group `G` acting transitively on the roots
  in `S` is generated by inertia subgroups, then `G` surjects onto the symmetric group of the roots
  in `S`.

The collisions modulo `m` are counted by the image of the roots in `S ⧸ m`. Where `f` splits in `S`
and does not vanish modulo `m`, this image is the set of roots of `f` in `S ⧸ m`
(`Polynomial.Splits.image_rootSet_of_map_ne_zero`).

Such polynomials are called *Morse functions* in Section 4.4 of [serre-galois].

## TODO

- Specialize to the case of number fields where generation by inertia subgroups is a consequence
  of Minkowski's theorem.
- Show that the Selmer polynomials `X ^ n - X - 1` have Galois group `S_n`.

## References

* [J. P. Serre, *Topics in Galois Theory*][serre-galois], Section 4.4

-/

public section

namespace Polynomial

variable {R S : Type*} [CommRing R] [CommRing S] [Algebra R S] [IsDomain S]
  {G : Type*} [Group G] [MulSemiringAction G S] [SMulCommClass G R S] {f : R[X]}

set_option backward.isDefEq.respectTransparency false in
/-- If the roots of `f` in `S` have at most one collision modulo an ideal `p`, then an element of
the inertia subgroup of `p` acts on the roots in `S` as the identity permutation or a
transposition.

Such polynomials are called *Morse functions* in Section 4.4 of [serre-galois]. -/
theorem toPermHom_apply_eq_one_or_isSwap_of_ncard_le_of_mem_inertia
    (hf0 : f.map (algebraMap R S) ≠ 0) [DecidableEq (f.rootSet S)] (p : Ideal S)
    (hp : (f.rootSet S).ncard ≤ (Ideal.Quotient.mk p '' f.rootSet S).ncard + 1)
    (g : G) (hg : g ∈ p.inertia G) :
    MulAction.toPermHom G (f.rootSet S) g = 1 ∨ (MulAction.toPermHom G (f.rootSet S) g).IsSwap := by
  classical
  rw [Set.ncard_le_ncard_image_add_one_iff] at hp
  have hπ (x : S) : Ideal.Quotient.mk p (g • x) = Ideal.Quotient.mk p x :=
    (Ideal.Quotient.mk_eq_mk_iff_sub_mem (g • x) x).mpr (hg x)
  rw [or_iff_not_imp_left, Equiv.ext_iff, not_forall]
  rintro ⟨x, hx : g • x ≠ x⟩
  refine ⟨g • x, x, hx, ?_⟩
  ext z
  simp only [Equiv.swap_apply_def, MulAction.toPermHom_apply, MulAction.toPerm_apply]
  split_ifs with hz hz'
  · subst hz
    have key := hp (g • g • x) (g • g • x).2 (g • x) (g • x).2 (g • x) (g • x).2 x x.2
      (by simp [hπ]) (by simp [hπ]) (by simpa [← rootSet.coe_smul]) (by simpa [← rootSet.coe_smul])
    grind [rootSet.coe_smul]
  · simp [hz']
  · grind [rootSet.coe_smul, SetLike.coe_eq_coe]

/-- If the roots of `f` in `S` have at most one collision modulo each maximal ideal `m`, and if a
group `G` acting transitively on the roots in `S` is generated by inertia subgroups, then `G`
surjects onto the symmetric group of the roots in `S`.

Such polynomials are called *Morse functions* in Section 4.4 of [serre-galois]. -/
theorem surjective_toPermHom_of_iSup_inertia_eq_top (hf0 : f.map (algebraMap R S) ≠ 0)
    [MulAction.IsPretransitive G (f.rootSet S)]
    (h : ∀ m : MaximalSpectrum S,
      (f.rootSet S).ncard ≤ (Ideal.Quotient.mk m.asIdeal '' f.rootSet S).ncard + 1)
    (hG : ⨆ m : MaximalSpectrum S, m.asIdeal.inertia G = ⊤) :
    Function.Surjective (MulAction.toPermHom G (f.rootSet S)) := by
  classical
  apply surjective_of_isSwap_of_isPretransitive'
      (⋃ m : MaximalSpectrum S, m.asIdeal.inertia G)
  · intro σ hσ
    obtain ⟨m, hm⟩ := Set.mem_iUnion.mp hσ
    exact toPermHom_apply_eq_one_or_isSwap_of_ncard_le_of_mem_inertia hf0 m.asIdeal (h m) σ hm
  · simpa [Subgroup.closure_iUnion]

end Polynomial
